### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by sternenseemann**

### CODE REVIEW

**Comment by sternenseemann** [comment]
Fingers crossed! Alternative to the patch thingy would be to move the examples into normal code blocks which bugs me because it is semantic markup after all…

**Review by peti — COMMENTED** [review]
Why do you add a patch instead of using the `--doctest-version=">0.18"` command line flag?

**Comment by sternenseemann** [comment]
I couldn’t get it to work even when building haskell-ci from master. Did you use a fork or something previously?

**Review by maralorn — APPROVED** [review]
If you say that the flag peti suggest doesn‘t work I am fine with merging this patch. It’s not pretty, but it’s not like we will touch this very often.

**Comment by sternenseemann** [comment]
See <https://github.com/haskell-CI/haskell-ci/issues/508>, no idea how peti got this to work to be honest. Had to resort to patching for cabal2nix's repository as well unfortunately.

Long term we may want to have nix-based CI, but that has a few possible pitfalls, so keeping haskell-ci is easier for now.

**Pull request merged**
